# server
server:
  port: 9090

# log
logging:
  level: debug


# spring
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/veges
    username: root
    password: 111111
    dbcp2:
      initial-size: 1
      min-idle: 1
      max-total: 20
  http:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization: true

# pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

# mybatis
mybatis:
  type-aliases-package: dhu.sun.vege.entity
  mapper-locations: classpath:mapper/*.xml

# mapper
mapper:
    mappers:
        dhu.sun.vege.util.core.BaseMapper
    not-empty: false
    identity: MYSQL

# JWT
jwt:
  header: Authorization
  secret: 12$#jI78Lb*(^%BC~
  expiration: 10 #单位小时
  tokenHead: Bearer
  route:
    authentication:
      path: auth/login
      refresh: auth/refresh
      register: auth/register